# Generated by Django 3.2.16 on 2022-12-27 13:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400)),
                ('category', models.CharField(choices=[('Film & Animation', 'Film & Animation'), ('Autos & Vehicles', 'Autos & Vehicles'), ('Music', 'Music'), ('Pets & Animals', 'Pets & Animals'), ('Sports', 'Sports'), ('Travel & Events', 'Travel & Events'), ('Gaming', 'Gaming'), ('People & Blogs', 'People & Blogs'), ('Comedy', 'Comedy'), ('Entertainment', 'Entertainment'), ('News & Politics', 'News & Politics'), ('Howto & Style', 'Howto & Style'), ('Education', 'Education'), ('Science & Technology', 'Science & Technology'), ('Nonprofits & Activism', 'Nonprofits & Activism')], max_length=21)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('video_file', models.FileField(upload_to='videos_and_thumbnails')),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.video')),
            ],
        ),
    ]
