# Generated by Django 4.0.4 on 2022-12-24 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_rating_rating_alter_video_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='average_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
